name: Build and publish Dev Release Work Item Tree

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: sudo npm install -g tfx-cli
    - run: npm run build:dev --if-present
    - uses: cschleiden/replace-tokens@v1
      with:
        files: '["**/*.json"]'
      env:
        PUBLISHER: mikeb
        EXTENSIONID: release-workitemtree
        EXTENSIONNAME: 'Dev: Release Work Item Tree'
    - run: tfx extension create --manifest-globs azure-devops-extension.json src/**/*.json --overrides-file configs/dev.json

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-workitemtree
        path: ${{ github.workspace }}/**/*.vsix
  publish:
    if: contains(github.event.pull_request.labels.*.name, 'publish')

    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: release-workitemtree

      - run: sudo npm install -g tfx-cli
      - run: tfx extension publish --vsix *.vsix --token ${{ secrets.PUBLISHERSTOKEN }} --rev-version
env:
  CI: true
