# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: sudo npm install -g tfx-cli
    - run: npm run build:dev --if-present
    - uses: cschleiden/replace-tokens@v1
        with:
          files: '["**/*.json"]'
        env:
          PUBLISHER: mikeb
          EXTENSIONID: release-workitemtree
    - run: tfx extension create --manifest-globs azure-devops-extension.json src/**/*.json --overrides-file configs/dev.json

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: release-workitemtree
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}/**/*.vsix
  publish:
    if: contains(github.event.pull_request.labels.*.name, 'publish')

    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: release-workitemtree
      #Remove later
      - run: ls -R
      - run: sudo npm install -g tfx-cli
      - run: tfx extension publish --vsix *.vsix --token ${{ secrets.PUBLISHERSTOKEN }} --rev-version
env:
  CI: true
